accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    term_date = models.DateTimeField('date term')
    question_short_description = models.CharField(max_length=200)
    question_full_description = models.CharField(max_length=200)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def will_be_removed(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.term_date <= now

    will_be_removed.admin_order_field = 'term_date'
    will_be_removed.boolean = True
    will_be_removed.short_description = 'Remove soon?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Voted(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question.question_text

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

polls/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice, Voted
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.exclude(term_date__lte = timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

        voteds = Voted.objects.all()
        for v in voteds:
            if v.user == request.user and v.question.id == question_id:
                return render(request, 'polls/results.html', {
                    'question': question,
                    'error_message': "Вы уже голосовали в этом опросе",
                })
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Вы ничего не выбрали",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        voted = Voted(question=question, user=request.user)
        voted.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

accounts/templates/accounts/signup.html
{% load static %}

{% include "head.html" %}

<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>

polls/templates/polls/detail.html
{% include "head.html" %}

<h1>{{ question.question_text }}</h1>
<p>{{ question.question_full_description }}</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

{% include "head.html" %}

<h1 class="d-flex justify-content-center mb-4">Опросы:</h1>

{% if request.user.is_authenticated %}

    {% if latest_question_list %}
        <div class="quests_wrap">
            <ul class="wrap-q">
                {% for question in latest_question_list %}

                    <li>
                        <a href="{%url 'polls:detail' question.id %}">
                            {{ question.question_text }}
                            <p>{{ question.question_short_description }}</p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% else %}

    <h3>Пожалуйста авторизируйтесь</h3>

{% endif %}

polls/templates/polls/results.html
{% include "head.html" %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <h2>{{ error_message }}</h2>
{% endif %}

<ul>

{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}

</ul>

{#<a href="{% url 'polls:detail' question.id %}">Vote again?</a>#}

templates/head.html
{% load static %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{% static 'polls/images/pizza.png' %}" type="image/png">
    <meta charset="UTF-8">
    <title>Castle of Polls</title>
</head>

<nav class="nav nav-pills flex-column flex-sm-row">
    <a class="flex-sm-fill text-sm-center nav-link col-1" href="{% url 'polls:index' %}">Главная</a>
    <a class="flex-sm-fill text-sm-center nav-link col-1" href="{% url 'accounts:signup' %}">Регистрация</a>

    <div class="col-8"></div>

    <div class="flex-sm-fill text-sm-center nav-link col-2">
        {% if user.is_authenticated %}
            <li>{{ user.get_username }}</li>
            <li><a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">Выйти</a></li>
        {% else %}
            <li><a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Авторизация</a></li>
        {% endif %}
    </div>
</nav>